# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 75505f30b198fd7212bcd0f64b5359fd7ae5c2210c1ea8cabc53e42c752235c9c4341252309fa432c7c3cb2dd91d9d17851a2b096f0046777dbbb7670e36d00a

test:
  secret_key_base: 4983a320e3b8682c5df8fac2fd08170c04aadee0e84d3bb2a1789c7881a1bd1989cf357924163a30d6f7ce9c0b9e8deed57c14c8a2fa457c52ba7626525a9cbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
